Azure/azure-linux-automation

- Azure_ICA_all.xml
- remote-scripts/ICA-BUILD-LINUX-KERNEL.ps1
- remote-scripts/Perf_BuildKernel.sh
This test script will update the kernel with either given tar or Linux-Next.
> Added new test script for preparing an image from latest Linux kernel Linux next

- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.ps1
- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.py
1.  Added support to add data disks while creating VM
2.  Updated BVT-VERIFY-VHD-PREREQUISITES for core os.
> CoreOS update + new feature added to Deploy VM.

- Azure_ICA_all.xml
- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-IS-ROOT-PASSWORD-DELETED.py
- remote-scripts/BVT-VERIFY-BOOT-ERROR-WARNINGS.ps1
- remote-scripts/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
- remote-scripts/BVT-VERIFY-UUID-FSTAB.py
- remote-scripts/LIS-LogCollector.sh
- remote-scripts/NETWORK-LB-NO-PROBE-PORT-IPERF-TCP-PARALLEL.ps1
- remote-scripts/VNET-IPERF-UDP-LOCAL-TO-VNET-ACCESS.ps1
- remote-scripts/VNET-PING-LOCAL-TO-VNET-ACCESS.ps1
- remote-scripts/ignorable-boot-errors.xml
1. CoreOS fix for BVT-IS-ROOT-PASSWORD-DELETED and BVT-VERIFY-UUID-FSTAB cases
2.  Add support for ignorable boot error messages, in BVT-VERIFY-BOOT-ERRORS
3. Update LIS-LogCollector.sh for CoreOS
4. Minor fix for CoreOS VNET cases
> Update for CoreOS

- AzureAutomationManager.ps1
- TestLibs/RDFELibs.psm1
- remote-scripts/GetLogFromDataDisk.py
- remote-scripts/SETUP-INSTALL-PACKAGES.ps1
- remote-scripts/SETUP-INSTALL-PACKAGES.py
> CoreOS image preparation + collect logs when VM provision failed in image preparation

- TestLibs/RDFELibs.psm1
Fixed : RetryOperation running infinitely in case of exception.
Fixed : WaitFor function not executing in case of exception.
> Fix : RetryOperation()

- SetupScripts/DetectLinuxDistro.sh
- remote-scripts/BVT-IS-ROOT-PASSWORD-DELETED.py
- remote-scripts/BVT-SWAP-CHECK.py
- remote-scripts/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
- remote-scripts/BVT-VERIFY-SSHD-CONFIG.py
- remote-scripts/BVT-VERIFY-UUID-FSTAB.py
- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.ps1
- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.py
- remote-scripts/ignorable-boot-errors.xml
- remote-scripts/packages.xml
Refine BVT test cases.
-BVT-IS-ROOT-PASSWORD-DELETED
-BVT-SWAP-CHECK
-BVT-VERIFY-BOOT-ERROR-WARNINGS
-BVT-VERIFY-SSHD-CONFIG
-BVT-VERIFY-UUID-FSTAB
-BVT-VERIFY-VHD-PREREQUISITES
> Refine BVT test cases

- Azure_ICA_all.xml
- TestLibs/RDFELibs.psm1
- remote-scripts/NETWORK-IDNS-SINGLEHS-CHANGED-HOSTNAME.ps1
- remote-scripts/SETUP-INSTALL-PACKAGES.py
• Fix case for NETWORK-IDNS-SINGLEHS-CHANGED-HOSTNAME
• Fix IsIperfServerStarted function, it will return -1 in some distro
• Fix case NETWORK-LB-CUSTOMPROBE-OTHER-PORT-TWO-NODES-DOWN-TCP abort for lack of stop-client.py
> Three fixes for network cycle

- AzureTestSuite.ps1
- TestLibs/RDFELibs.psm1
- remote-scripts/SETUP-INSTALL-PACKAGES.py
- remote-scripts/azuremodules.py
- remote-scripts/packages.xml
1. install iperf from RPM package for OpenSUSE 13.2
2. Fix the cleanup and failure-preserving issues of Economy mode
> 1. install iperf from RPM package for OpenSUSE 13.2

- Azure_ICA_all.xml
- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-VERIFY-MNT-RESOURCE-README.ps1
- remote-scripts/BVT-VERIFY-MNT-RESOURCE-README.py
- remote-scripts/BVT-VERIFY-NO-ERROR-IN-LOGS.ps1
- remote-scripts/BVT-VERIFY-NO-ERROR-IN-LOGS.py
- remote-scripts/BVT-VERIFY-VERBOSE-ENABLED-LOGS.ps1
- remote-scripts/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
- remote-scripts/E2E-WA-UNINST.ps1
- remote-scripts/E2E-WA-UNINST.py
•         BVT-VERIFY-MNT-RESOURCE-README
•         BVT-VERIFY-NO-ERROR-IN-LOGS
•         BVT-VERIFY-VERBOSE-ENABLED-LOGS
•         E2E-WA-UNINST
in addition, fix code exception of TC "NETWORK-IE-TCP-SINGLE-HS" happen on some distros.
> Move 4 FC cases to Cloud

- TestLibs/AzureWinUtils.psm1
- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-MTAB-ENTRY-CHECK.py
- remote-scripts/BVT-VERIFY-VERBOSE-ENABLED-LOGS.ps1
- remote-scripts/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
1. Update the log timestamp to 24 hours format
2. Minor update for case BVT-MTAB-ENTRY-CHECK and BVT-VERIFY-VERBOSE-ENABLED-LOGS
> Minor fixes

- Azure_ICA_all.xml
This will deploy 10 VMs of each size for more extensive testing. (Successfully deployed VMs will be automatically deleted.)
> Changed Deployment count to 250.

- remote-scripts/BVT-RESOURCE-DISK-FILESYSTEM.py
- remote-scripts/BVT-VERIFY-DISKSIZE.py
- remote-scripts/azuremodules.py
fix issue caused by the exchanged order of the OS disk and resource disk in CoreOS
> fix issue caused by the exchanged order of the OS disk and resource disk in CoreOS

- Azure_ICA_all.xml
- remote-scripts/BVT-VERIFY-NO-ERROR-IN-LOGS.ps1
- remote-scripts/BVT-VERIFY-NO-ERROR-IN-LOGS.py
- remote-scripts/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
minor adjust BVT test order and improve code
> minor adjust BVT test order and improve code

- Azure_ICA_all.xml
- TestLibs/RDFELibs.psm1
- remote-scripts/E2E-CHANGE-USER-PASSWORD.ps1
- remote-scripts/E2E-HOT-ADD-REMOVE-EXISTING-DATA-DISK-PARALLEL.ps1
- remote-scripts/E2E-HOT-ADD-REMOVE-EXISTING-DATA-DISK-SERIAL.ps1
- remote-scripts/E2E-HOT-ADD-REMOVE-NEW-DATA-DISK-PARALLEL.ps1
- remote-scripts/E2E-HOT-ADD-REMOVE-NEW-DATA-DISK-SERIAL.ps1
- remote-scripts/E2E-VM-CAPTURE-IMAGE-WITH-WAAGENT-DEPROVISION.ps1
1.Added DS series support to E2E disk test cases (DS11,DS12,DS13,DS14
will be added in next commit)
2.Fixed bug E2E-CHANGE-USER-PASSWORD (failing to collect final dmesg
logs, test was failing for some distros due to unmatched string "updated
successfully.")
3.Fixed issue in E2E-VM-CAPTURE test.
4.Updated PerformIOTestOnDisk(). [DoIoTest.py was failing for SLES
distros.]
> Automation Improvements

- TestLibs/RDFELibs.psm1
- remote-scripts/ICA-DEPLOYMENT-ALL-SIZES-LOOP-TEST.ps1
[NEW] Deployment test now reports more performance data such as -
+VM deployment time [time taken to report that VM is created.]
+VM boot time [VM started > VM accessible for SSH.]
+VM Provision time. [VM booted > VM status is ReadyRole]
Test will also report avg, min, max time stamps for deployment, boot and
provision.
> Improved Deployment Loop Test

- Azure_ICA_all.xml
- remote-scripts/BVT-VERIFY-RESTART.ps1
Updated test definitions of LIS4 test and Custom Script extension test.
> Minor Fix.

- remote-scripts/NETWORK-IDNS-SINGLEHS-CHANGED-HOSTNAME.ps1
fix bug of NETWORK-IDNS-SINGLEHS-CHANGED-HOSTNAME
> fix bug of NETWORK-IDNS-SINGLEHS-CHANGED-HOSTNAME

- Azure_ICA_all.xml
- SetupScripts/DetectLinuxDistro.sh
- TestLibs/ARMLibrary.psm1
- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-WA-VER-CHECK.py
- remote-scripts/SETUP-INSTALL-PACKAGES.ps1
- remote-scripts/SETUP-INSTALL-PACKAGES.py
- remote-scripts/azuremodules.py
update code for ARM module and new distro
> update code for ARM module and new distro

- SetupScripts/DetectLinuxDistro.sh
- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.ps1
- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.py
- remote-scripts/SETUP-INSTALL-PACKAGES.py
- remote-scripts/azuremodules.py
- remote-scripts/ignorable-boot-errors.xml
- remote-scripts/packages.xml
add distro 'debian' and fix some image preparing issue
> add distro 'debian' and fix some image preparing issue

- remote-scripts/azuremodules.py
fix issue about the package 'ntp' installation output info does not match with the regular expression in the script.
> fix image prepare issue for Debian

- remote-scripts/ICA-OS-PATCHING-EXTENSION-TEST.ps1
> minor fix of os patching ext test

- remote-scripts/SETUP-INSTALL-PACKAGES.py
- remote-scripts/packages.xml
1. check requisite test packages.
2. update pkg info for sles.
> trigger test while inessential pkg-inst failure

- Azure_ICA_all.xml
- remote-scripts/BVT-VERIFY-BASH-HISTORY.ps1
- remote-scripts/BVT-VERIFY-BASH-HISTORY.py
- remote-scripts/SETUP-INSTALL-PACKAGES.ps1
1. add case.
2. copy the default bash history file for testing.
> Add new TC: BVT-VERIFY-BASH-HISTORY

- Azure_ICA_all.xml
- TestLibs/ARMLibrary.psm1
- remote-scripts/Template-cloudera-centos.ps1
- remote-scripts/Template-datastax-enterprise.ps1
1. add cases for templates(datastax-enterprise, cloudera-on-centos)
2. add the case BVT-VERIFY-BASH-HISTORY and the case for CustomScript extension to the CI Runner test cycle
> add cases for templates and add some cases to CI Runner test cycle

- remote-scripts/BVT-VERIFY-BOOT-ERROR-WARNINGS.ps1
- remote-scripts/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
- remote-scripts/ignorable-boot-errors.xml
merge content of file ignorable-boot-errors.xml for different distros
> merge content of file ignorable-boot-errors.xml for different distros

- remote-scripts/ignorable-boot-errors.xml
add a new ignorable error info to ignorable-boot-errors.xml
> add a new ignorable error info to ignorable-boot-errors.xml

- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.py
- remote-scripts/ignorable-boot-errors.xml
add a new ignorable fail info and do some minor fix
> add a new ignorable fail info and do some minor fix

- remote-scripts/azuremodules.sh
To avoid python2 python3 compatibility issues its better to develop upcoming testcases in bash. We can use this library for common functionalities in bash scripts.
> A library for common tasks performed in bash scripts.

- Azure_ICA_all.xml
- TestLibs/ARMLibrary.psm1
- TestLibs/AzureWinUtils.psm1
- TestLibs/RDFELibs.psm1
- remote-scripts/ICA-RHUI-ALL-REGION-TEST.ps1
- remote-scripts/ICA-RHUI-ALL-REGION-TEST.py
Add case ICA-RHUI-ALL-REGION-TEST
- Set up VMs using gallery image in different regions 
- Check gcc can be downloaded
- Check no error and have extras in yum repolist
- Get all CDS servers
- Get the latency value list between test machine and target CDS server using nmap
- If needed, run stress test for 1 hour by set RunDownload section in xml file
> Add case for ICA-RHUI-ALL-REGION-TEST

- remote-scripts/BVT-VERIFY-DISKSIZE.ps1
- remote-scripts/BVT-VERIFY-DISKSIZE.py
Actual size used is Byte, but was named as KB.
> Fix disk size unit.

- remote-scripts/azuremodules.sh
- remote-scripts/sysbench-full-io-test.sh
- remote-scripts/sysbench-log-parser.sh
Added Max IOPS finding logic for each mode and block size and some other minor fixes.
> Added Max IOPS finding logic for each mode and block size

- Azure_ICA_all.xml
add case ICA-VERIFY-BILLING-TAG configuration
> add case ICA-VERIFY-BILLING-TAG

- TestLibs/RDFELibs.psm1
- remote-scripts/BVT-MTAB-ENTRY-CHECK.py
- remote-scripts/BVT-RESOURCE-DISK-FILESYSTEM.py
- remote-scripts/BVT-VERIFY-MNT-RESOURCE-WRITABLE.py
- remote-scripts/azuremodules.py
1. Improve 3 BVT cases about resource disk check.
- BVT-MTAB-ENTRY-CHECK
- BVT-RESOURCE-DISK-FILESYSTEM
- BVT-VERIFY-MNT-RESOURCE-WRITABLE
2. Fix exception in checking provision VM failed in service.
> bvt fixes related to resource disk and test library

- TestLibs/RDFELibs.psm1
- remote-scripts/ICA-PASSWD-POLICY-TEST.py
- remote-scripts/ignorable-walalog-errors.xml
> password policy test for RHEL

- remote-scripts/azuremodules.py
> change the way of detect if cloud-init handle provision

- TestLibs/RDFELibs.psm1
- remote-scripts/azuremodules.py
- remote-scripts/packages.xml
Fix for plink issue against Oracle72 and Debian
Fix for the distribution value contains blank in Oracle 6.7
Fix no nslookup/dig commands in Oracle image in prepare job, install needed package
> Fix for plink issue against Oracle72 and Debian

- remote-scripts/ICA-VERIFY-RDMA.py
> update RDMA case for CentOS

- AzureAutomationManager.ps1
- Azure_ICA_all.xml
- TestLibs/AzureWinUtils.psm1
- TestLibs/RDFELibs.psm1
> minor fix code for mooncake

- remote-scripts/BVT-VERIFY-VHD-PREREQUISITES.py
fix the issue https://github.com/Azure/azure-linux-automation/issues/186
> fix the issue https://github.com/Azure/azure-linux-automation/issues/186

- Azure_ICA_all.xml
- TestLibs/RDFELibs.psm1
- remote-scripts/CleanupDnsServer.py
- remote-scripts/ConfigureDnsServer.py
- remote-scripts/VNET-IPERF-UDP-INTRAVNET-ACCESS.ps1
- remote-scripts/VNET-IPERF-UDP-LOCAL-TO-VNET-ACCESS.ps1
- remote-scripts/VNET-IPERF-UDP-VNET-TO-LOCAL-ACCESS.ps1
- remote-scripts/VNET-PING-INTRAVNET-ACCESS.ps1
- remote-scripts/VNET-PING-LOCAL-TO-VNET-ACCESS.ps1
- remote-scripts/VNET-PING-VNET-TO-LOCAL-ACCESS.ps1
- remote-scripts/VNET-VERIFY-REMOTE-SSH-SCP-INTRAVNET-ACCESS.ps1
- remote-scripts/VNET-VERIFY-REMOTE-SSH-SCP-LOCAL-TO-VNET-ACCESS.ps1
Update code due to VNET test environment changed to 'VNET to VNET'
> Update code due to VNET test environment changed to 'VNET to VNET'

- remote-scripts/SETUP-INSTALL-PACKAGES.py
Fix issue for waagent process dead in centos68 during prepare image
> Add start waagent service for centos

- remote-scripts/E2E-DAYTRADER-SETUP.py
- remote-scripts/ICA_VMSetup.sh
- remote-scripts/mariadb_perf_server_conf.sh
It's an archived repo, for backup and reference purpose only.
Change it to avoid security concern.
> Change chmod 777 to 755
